name: 'HTML Preview Action'

on: [pull_request]

jobs:
  html_preview:
    runs-on: ubuntu-latest
    name: HTML Preview
    steps:
      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
